delete from major;

-- Insert into major

insert into major (name, description) values ('Accounting', 'Designed to prepare students to perform accounting activities for corporations, governmental agencies, nonprofit organizations or individuals, this program allows the student to focus on specific areas of interest in the accounting profession. Upon successful completion of the program, students will have a strong background in accounting principles and applications, as well as a strong general education experience.');
insert into major (name, description) values ('Art + Design', 'The Art Design program offers students an Associate of Arts degree and preparation to transfer to a B.A. or B.F.A. Art+Design program. This program challenges students with an intensive, hands-on, studio-based curriculum that emphasizes art making skills and critical thinking. Classes are taught by professional, exhibiting artists who have expertise in their disciplines. This program also provides the community with the opportunity to study for personal enrichment.');
insert into major (name, description) values ('Biology', 'This program offers biology students courses in natural and physical sciences in preparation for a wide array of career opportunities. Biological scientists study the origin, development, characteristics, and life processes of plant, microbial, and animal life and their relationships to the environment. They may conduct basic research aimed at increasing our knowledge of living organisms or applied research in medical and industrial settings. A major in the biological sciences is recommended for students interested in pursuing further study in biology, biotechnology and related fields, botany, zoology, microbiology, forestry, molecular and cellular biology, genetics, marine biology, high school biology teaching, and more. This program provides an excellent foundation for studies in pre-professional fields such as pre-medicine, pre-dentistry, pre-pharmacy, physical therapy, occupational therapy, and pre-veterinary sciences.');
insert into major (name, description) values ('Business Administration', 'This program is designed for students who wish to transfer to earn a baccalaureate degree in some area of business. Students who plan to transfer should consult an advisor for assistance in selecting courses appropriate for the transfer institution and program. The courses in this curriculum prepare students for later specialization in finance, human resource management, management, private and public accounting, marketing, merchandising and advertising. Cooperative Education is available to students in this program as an additional means of receiving extended learning experiences related to Business Administration.');
insert into major (name, description) values ('Chemistry', 'The chemistry program is designed to prepare students for transfer to a Bachelor''s degree program in general chemistry, forensic chemistry, medicinal chemistry, environmental science/chemistry, and more. Chemists investigate the composition, structure and properties of substances and the transformations they undergo, through basic, as well as applied, research toward the development of new products and methods of producing new materials. They also work in biotechnology, drug development, forensic science, and other areas where a strong foundation in chemistry is essential.');
insert into major (name, description) values ('Communications Studies', 'Students of this program will develop an understanding of core communication concepts and apply them in a wide variety of many different careers, relationships, and settings. Because skilled communicators are highly desired by business and industry, students may go on to hold a variety of positions in a wide range of fields and/or to a four year Communication Studies Degree Program.');
insert into major (name, description) values ('Computer Aided Design and Drafting (CADD)', 'This program provides students with a sound knowledge of Computer Aided Design and Drafting (CADD) through familiarization with the computer, peripheral devices and specialized software. The program prepares students to function as skilled CADD professionals who assist engineers and architects in all design and drawing preparation phases.');
insert into major (name, description) values ('Computer Information Systems', 'Computer Information Systems (CIS) is the study of the use of computers in business applications. The CIS curriculum presents computer literacy, program design, programming languages and electives in software, network and Internet applications. CIS students may pursue careers as computer programmers, computer simulation/gaming engineers, software specialists, computer user support specialists, network and Internet specialists.');
insert into major (name, description) values ('Computer Science', 'Computer Science is the study of the design, theory and programming of the computer system. The Computer Science program gives students an understanding of the problem-solving techniques used to program the computer as well as an understanding of the principles that govern the conceptual organization of the computer system and its processes. The program emphasizes the mathematical and scientific components of programming.');
insert into major (name, description) values ('Criminal Justice', 'The A.A. degree option in Criminal Justice is designed to prepare students for transfer to baccalaureate programs with majors in Criminal Justice. This option provides students an overview of various aspects of the Criminal Justice major and prepares students to complete the last two years at a four-year institution.');
insert into major (name, description) values ('Early Childhood Education', 'This program prepares students for employment in the child care industry in a management/leadership position. Students will have the opportunity to specialize in teaching or in site management of a child care center. There are two required field placement experiences (135 hours each) in teaching in a child care program/school and site management of a child care center.');
insert into major (name, description) values ('Engineering', 'This curriculum is designed to meet the needs of students who plan to transfer to a college or university that grants a baccalaureate degree in engineering. Engineers apply the principles of science and mathematics to develop economical solutions to technical problems. Their work is the link between social needs and commercial applications. In addition to design and development, many engineers work in testing, production, or maintenance.');
insert into major (name, description) values ('English', 'This curriculum is designed for students in the arts and sciences who plan to transfer to a baccalaureate degree institution for their upper division major. The core courses provide a foundation in academic writing and literary studies.');
insert into major (name, description) values ('Environmental Science', 'The A.S. degree in Environmental Science offers students the opportunity to transfer to a senior institution as well as to gain applied skills in order to compete in the job market for technical positions. Environmental scientists engage in work to protect the environment, study the properties of underground and surface waters, locate water and energy resources, predict water-related geologic hazards, and offer environmental site assessments and advice on indoor air quality and hazardous-waste- site remediation.');
insert into major (name, description) values ('General Studies', 'The General Studies program permits students to pursue a structured program that allows them to achieve a balance between depth of knowledge acquired through specialization in a twelve-credit concentration in a single field of knowledge and breadth of knowledge gained through exploration of various disciplines.');
insert into major (name, description) values ('History', 'This option provides traditional freshman and sophomore year courses for history majors and other liberal arts majors transferring to four-year colleges or universities. The curriculum provides students with an understanding of their political, social, economic, intellectual, scientific and artistic heritage.');
insert into major (name, description) values ('Information Systems Management', 'nformation Systems Management emphasizes business, organizational and management concepts as well as computer technology skills. Coursework in areas such as business fundamentals, accounting, finance, marketing, production, management, computer programming, systems analysis and design, database concepts, and management and data communications are typical for a degree in ISM. Students learn how to analyze, design and implement information systems that will provide managers with the information needed to make operational and strategic decisions for large and small companies.');
insert into major (name, description) values ('Information Assurance and Cybersecurity', 'This degree program prepares students to enter the high-demand field of information technology security. With the increase of viruses and other security breaches, companies need professionals who can protect their data and equipment from internal and external security threats. Students in this program gain hands-on experience with the latest hardware and software and learn to implement appropriate security policies and procedures. Students planning to transfer should select electives according to the requirements of the receiving institution.');
insert into major (name, description) values ('Mass Communications', 'Designed to prepare students for entry-level employment in social media, new media, marketing, advertising sales and promotion or for transfer to a four-year institution, this program emphasizes the business aspects of the media, including sales, advertising, marketing, promotion, and management.');
insert into major (name, description) values ('Mathematics', 'This program provides a solid background for those who wish to pursue a course of study in mathematics. Students will develop an understanding of the ethical, societal, historical and global implications of mathematical concepts. Mathematicians use mathematical theory, computational techniques, algorithms, analysis and the latest computer technology to solve economic, scientific, engineering, physics, and business problems. They conduct research in fundamental mathematics and use the application of mathematical techniques to solve problems in other fields such as science, actuarial science and risk management.');
insert into major (name, description) values ('Medical Assisting', 'The Associate of Applied Sciences degree in Medical Assisting is a career program designed to prepare students for employment as medical assistants immediately upon completing the course of studies. The program prepares students to work in an administrative and clinical capacity in a variety of medical office and clinical settings. Students learn the knowledge, technical skills and work ethic that are required for an entry level position in medical assisting. The program includes both classroom theory and clinical practice. Graduates of the program are eligible to test for the Registered Medical Assistant (RMA) through American Medical Technologists (AMT) or the Certified Medical Assistant (CMA) through American Association of Medical Assistants (AAMA). Please note that, generally, individuals who have been found guilty of a felony, or pleaded guilty to a felony, are not eligible to take the exam. However, the Certifying Board may grant a waiver based upon mitigating circumstances.');
insert into major (name, description) values ('Music', 'This program provides a variety of opportunities and courses for students who wish to study music either as preparation for a profession in one of the many career fields or for personal enrichment.');
insert into major (name, description) values ('Nursing', 'The Associate of Sciences Degree Nursing Program prepares students for the licensure examination for registered nurses. Graduates of the Associate of Sciences Degree Nursing Program are eligible to take the National Council Licensure Examination for Registered Nurses (NCLEX-RN). The program also provides opportunities to plan for career mobility through courses that articulate with selected baccalaureate nursing programs in the state of Maryland.');
insert into major (name, description) values ('Paralegal Studies', 'A legal assistant or paralegal is a person, qualified by education, training, or work experience who is employed or retained by a lawyer, law office, corporation, governmental agency or other entity and who performs specifically delegated substantive legal work for which a lawyer is responsible. ABA Guideline G-103(d). Paralegals may not provide legal services directly to the public, except as permitted by law. The objective of the Paralegal Studies Option of the Legal Studies Program is to educate and train laypersons to assist attorneys and other legal professionals in their daily tasks and thereby contribute to the fair, economical and efficient delivery of legal services. The program meets this objective by requiring students to successfully complete its curriculum.');
insert into major (name, description) values ('Philosophy', 'This curriculum is designed for students in the arts and sciences who plan to transfer to a baccalaureate degree institution for their upper division major. The core courses constitute a foundation in the field of philosophy and challenge students to think clearly about issues and ideas derived not only from the historical Western intellectual heritage but also from present ideologies and problems.');
insert into major (name, description) values ('Physics', 'The physics program is designed to prepare students for transfer to a Bachelor’s degree in general physics or applied physics. Physicists seek to discover and describe the rules governing natural phenomena at all scales, from the sub-nuclear building blocks to the large-scale structure of the universe. They are concerned with the properties, changes and interactions of matter, energy and other physical phenomena. They conduct research into physical phenomena, develop theories and laws, and devise methods of applying the laws of physics to industry, medicine and other fields. Physicists may specialize in several areas such as astrophysics, bio- and medical physics, quantum physics, solid state physics, nuclear physics, acoustical physics, fluid and plasma physics, and education.');
insert into major (name, description) values ('Political Science', 'This option is designed primarily to prepare students for transfer to baccalaureate programs with majors in Political Science.');
insert into major (name, description) values ('Psychology', 'This option is designed to prepare students for transfer to baccalaureate programs with major emphasis on psychology and the behavioral sciences. Students planning careers in a variety of related fields may also use this option as a general program guide.');
insert into major (name, description) values ('Sociology', 'The Sociology program prepares students for a wide variety of careers in government, business, and non-profit organizations, such as research and demography, clinical and counseling services, applied anthropology, and human services. Students can choose from three track concentrations that have been developed to facilitate transfer to baccalaureate programs in sociology, social work, or anthropology.');
insert into major (name, description) values ('Teacher Education', 'This degree program prepares students for transfer into a four-year college or university education program in a specific area of study (e.g. biology, history, physical education, etc.). High school preparation should include four units of English, four units of math of which two should be algebra, and three units of science. Students should plan to take Praxis Core or an equivalent assessment near completion of 45 credits. Check with transfer institution for pre-professional test requirements.');
insert into major (name, description) values ('Theatre', 'The major in Theatre: Design/Production is time-consuming and physically demanding. Participation in productions is a part of the educational program. All majors must participate in theatre activities on weekends and during the evening.');