delete from department;

-- Insert into department
insert into department (code, name) values ('ACCT', 'Accounting');
-- insert into department (code, name) values ('AHS', 'Allied Health Sciences');
-- insert into department (code, name) values ('ASL', 'American Sign Language');
-- insert into department (code, name) values ('ANTH', 'Anthropology');
-- insert into department (code, name) values ('ART', 'Art + Design');
-- insert into department (code, name) values ('APL', 'Assessment for Prior Learning');
-- insert into department (code, name) values ('ASTR', 'Astronomy');
insert into department (code, name) values ('BIO', 'Biology');
insert into department (code, name) values ('BA', 'Business Administration');
insert into department (code, name) values ('CHEM', 'Chemistry');
insert into department (code, name) values ('CMST', 'Communication Studies');
-- insert into department (code, name) values ('CADD', 'Computer Aided Design &amp; Draft');
insert into department (code, name) values ('CIS', 'Computer Information Systems');
insert into department (code, name) values ('CSI', 'Computer Science');
insert into department (code, name) values ('CJ', 'Criminal Justice');
-- insert into department (code, name) values ('DRAM', 'Drama');
-- insert into department (code, name) values ('ES', 'Earth Science');
insert into department (code, name) values ('ECON', 'Economics');
insert into department (code, name) values ('EDUC', 'Education');
-- insert into department (code, name) values ('ELEC', 'Electronics');
insert into department (code, name) values ('ENGR', 'Engineering');
-- insert into department (code, name) values ('ENGT', 'Engineering Technology');
insert into department (code, name) values ('ENG', 'English');
-- insert into department (code, name) values ('ENV', 'Environmental Sciences');
-- insert into department (code, name) values ('FIN', 'Finance');
-- insert into department (code, name) values ('FS', 'Forensic Science');
-- insert into department (code, name) values ('FR', 'French');
-- insert into department (code, name) values ('GEOG', 'Geography');
-- insert into department (code, name) values ('GER', 'German');
-- insert into department (code, name) values ('HLTH', 'Health');
insert into department (code, name) values ('HIST', 'History');
-- insert into department (code, name) values ('HD', 'Human Development');
insert into department (code, name) values ('ISS', 'Information Systems Security');
-- insert into department (code, name) values ('IDS', 'Interdisciplinary Studies');
-- insert into department (code, name) values ('MC', 'Mass Communications');
insert into department (code, name) values ('MATH', 'Mathematics');
-- insert into department (code, name) values ('MAS', 'Medical Assisting');
-- insert into department (code, name) values ('MUS', 'Music');
-- insert into department (code, name) values ('NURS', 'Nursing');
-- insert into department (code, name) values ('OS', 'Office Systems');
-- insert into department (code, name) values ('ORIE', 'Orientation');
-- insert into department (code, name) values ('PL', 'Paralegal');
insert into department (code, name) values ('PHIL', 'Philosophy');
-- insert into department (code, name) values ('PHOT', 'Photography');
insert into department (code, name) values ('PE', 'Physical Education');
-- insert into department (code, name) values ('SCI', 'Physical Science');
insert into department (code, name) values ('PHYS', 'Physics');
insert into department (code, name) values ('PS', 'Political Science');
-- insert into department (code, name) values ('PN', 'Practical Nursing');
insert into department (code, name) values ('PSY', 'Psychology');
-- insert into department (code, name) values ('RELG', 'Religion');
insert into department (code, name) values ('SOC', 'Sociology');
-- insert into department (code, name) values ('SPAN', 'Spanish');
-- insert into department (code, name) values ('SDEV', 'Student Development');
-- insert into department (code, name) values ('THEA', 'Theatre');
-- insert into department (code, name) values ('VPA', 'Visual and Performing Arts');