insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lindsey","Swanson", 1971,1,1);		
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Donald","Cohen", 2000,0,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Robin","Norris", 1986,1,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jan","Mckenzie", 1987,1,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Edwin","Shelton", 1972,1,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Omar","Salazar", 2002,0,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Simon","Gilbert", 1983,1,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Alan","Anderson", 2009,0,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Desiree","Tucker", 1970,1,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Alexander","Snyder", 2012,0,1);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Winifred","Ellis", 1987,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ross","Park", 2005,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Elbert","Buchanan", 2013,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Monique","Green", 1989,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Roy","Garza", 1982,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rochelle","Mcbride", 1986,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Christine","Abbott", 2002,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Winston","Todd", 1977,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sharon","Glover", 2000,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Austin","Sandoval", 2006,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rosa","Dawson", 1997,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Stephanie","Vasquez", 1978,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Alexandra","Sanchez", 2008,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Amelia","Garner", 2007,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Hugh","Williams", 1984,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Dean","Byrd", 2013,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jacqueline","Hale", 2004,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jessie","Hunt", 1975,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jeannie","Erickson", 2009,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Doris","Huff", 1999,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Nadine","Burgess", 2013,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Shaun","Ingram", 2012,0,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ken","Torres", 1984,1,2);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Johnnie","Stevens", 1987,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Harold","Wolfe", 1976,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sammy","Russell", 1999,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Cory","Soto", 1999,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Clay","Ramirez", 1975,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Tracey","Gordon", 1975,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Gustavo","Haynes", 1981,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Willie","Thomas", 1973,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Candace","Lynch", 2000,0,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Erma","Lucas", 1988,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sonia","Moran", 2013,0,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Christopher","Wagner", 2001,0,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ellis","Aguilar", 1988,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Gwendolyn","Rice", 1992,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Eunice","Briggs", 2010,0,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Tommie","Douglas", 1993,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Garry","Figueroa", 1971,1,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Joan","Blake", 2005,0,3);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lorenzo","Brown", 1973,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lucille","Pittman", 2002,0,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sue","Hodges", 1994,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Evelyn","Mcguire", 1981,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Irving","Harvey", 1970,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Celia","Spencer", 1987,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rebecca","Garrett", 2008,0,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Josephine","Patton", 1982,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Barbara","Luna", 1980,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Elvira","Drake", 1981,1,4);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Andres","Simpson", 2009,0,5);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Tracy","Craig", 2006,0,5);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Nina","Rhodes", 1977,1,5);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Roland","Boone", 1977,1,5);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ron","Ramsey", 2005,0,5);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lynne","Castro", 1991,1,5);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kimberly","Pierce", 1984,1,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Mabel","Evans", 2005,0,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Shelia","Ruiz", 1983,1,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jackie","Sutton", 2009,0,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Phil","Logan", 2012,0,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kellie","Perkins", 1991,1,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ronnie","Myers", 2003,0,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Brendan","Hogan", 2007,0,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Oliver","Powers", 1972,1,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Joy","Richardson", 2011,0,6);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Tommy","George", 2009,0,8);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("George","Wade", 2011,0,8);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Mary","Potter", 2012,0,8);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Anthony","Johnston", 1982,1,8);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Terry","Harmon", 1981,1,8);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Wayne","Houston", 1977,1,9);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Barry","Daniel", 1971,1,9);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Bobby","Mathis", 2000,0,9);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Norman","Reynolds", 1977,1,10);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kenny","Hubbard", 1978,1,10);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Anne","Wise", 2008,0,10);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Caleb","Keller", 1972,1,10);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ronald","Morrison", 1992,1,10);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Dora","Obrien", 1988,1,11);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jody","Fowler", 2010,0,11);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Max","Williamson", 1975,1,11);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ignacio","Hart", 1977,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Abel","Newton", 1997,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Stewart","Griffin", 2006,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lora","Ford", 2001,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Charlie","Summers", 2010,0,12);	
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Billy","Woods", 1999,1,12);		
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jessie","Ortega", 1983,1,12);	
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sonja","Cox",2014,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Hattie","Mathis",1999,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lila","Hawkins",2001,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kristina","George",1990,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Martin","Gordon",1985,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Beverly","Quinn",2003,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Vera","Silva",2006,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Joshua","Fletcher",1997,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kim","Nguyen",1989,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Benjamin","Spencer",1994,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Wade","Rhodes",2002,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jill","Curtis",2008,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Robyn","Gardner",2011,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kelly","Hubbard",1982,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lana","Hill",1983,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Stephen","Webb",1984,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Carolyn","Mack",1986,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Meghan","Henderson",2004,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Mark","Ramirez",2005,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Virgil","Higgins",2007,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Joel","Fleming",2010,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Vernon","Fox",1993,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rudolph","Cole",1993,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Inez","Barnett",1994,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jane","Briggs",1996,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Violet","Ingram",1999,1,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lena","Boyd",2016,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Gabriel","Murphy",2016,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Marc","Daniel",2015,0,12);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ramiro","Webster",2015,0,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Cecilia","Thompson",2015,0,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Travis","Bowen",1991,1,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Bethany","Davidson",1996,1,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kenny","Duncan",1997,1,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Maureen","Alvarez",1992,1,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Gladys","Stone",1992,1,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Blanche","Baker",1981,1,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Crystal","Watkins",2001,0,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Boyd","Richardson",2002,0,13);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Della","Bowers",2002,0,14);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Colin","Bennett",2003,0,14);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jonathan","Hicks",2003,0,14);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Arlene","Rice",1993,1,14);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Bobby","Mcdaniel",1994,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Alicia","Carr",1998,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Brett","Becker",1996,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jack","Jordan",1994,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Francis","West",1990,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Abel","Hill",2004,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kari","Hunt",2002,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Celia","Watkins",2002,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Herman","Quinn",2004,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Cameron","Lopez",2010,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lorraine","Cole",2015,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sonja","Bowers",1983,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Maureen","Scott",1992,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Phyllis","Alvarado",1997,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Allan","Weaver",1998,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Joanna","Craig",2009,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Joan","Rodriguez",2016,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Milton","Huff",2013,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Brittany","Andrews",1996,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Amy","Hale",1995,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Miguel","Thompson",1994,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ronnie","Collins",2001,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Eddie","Haynes",2001,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Clayton","Marsh",2001,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Myra","Murphy",2002,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Pearl","Chambers",1985,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Phillip","Lawrence",1986,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Harvey","Manning",1986,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lindsay","Patterson",1981,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Cory","Perez",1990,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jim","Johnson",1993,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Olivia","Collier",2004,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Clint","Green",2015,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Anne","Hudson",2010,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kellie","Grant",2005,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Brenda","Flowers",2000,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jonathan","Ballard",1996,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Constance","Jacobs",1993,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Gordon","Gilbert",1990,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Alberta","Pearson",1987,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Irene","Bell",1986,1,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jana","Parker",2000,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Nora","Brewer",2002,0,15);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Morris","Alexander",2005,0,16);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jenna","Delgado",2007,0,16);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Terry","Sutton",2009,0,16);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Clark","Bowman",2002,0,16);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Van","Russell",1998,1,16);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Noah","Castillo",1994,1,16);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lorena","Williamson",1992,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Melissa","Hughes",1993,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rex","Harmon",1995,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Leah","Parks",1996,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Edwin","Ramirez",1988,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Angelica","Rodgers",2002,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kent","Miles",2006,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Becky","Morgan",2009,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Lois","Chandler",2012,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Patsy","Casey",2012,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kerry","Mckinney",2014,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Neil","Mcdaniel",1991,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sheldon","Bates",1991,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Julie","Strickland",1995,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jeanne","Watson",1996,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Darnell","Matthews",1997,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Irving","Paul",1998,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Doreen","Oliver",1979,1,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Cecelia","Lyons",2006,0,17);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Teresa","Cunningham",2000,0,18);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Angel","Buchanan",2002,0,18);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Marilyn","Fox",2006,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Jonathon","Bennett",2006,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Orville","Cook",2007,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rafael","Phillips",2010,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Loren","Burgess",2010,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Beth","Rowe",2013,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Teri","Garrett",1993,1,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sylvester","Malone",1987,1,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Vicki","Soto",2004,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ruth","Schultz",2013,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Theresa","Morales",1999,1,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Daniel","Hogan",1993,1,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Ismael","Carpenter",2003,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Sadie","Wilson",2006,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Julio","Herrera",2007,0,20);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Luis","Walters",1994,1,21);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Stephanie","Watts",1984,1,21);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Kerry","Washington",1999,1,21);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Merle","Walker",2002,0,21);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Dallas","Wagner",2004,0,21);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Rodolfo","Lloyd",2006,0,21);
insert into instructor (first_name, last_name, year_hired, is_tenured, department_id) values ("Drew","Payne",2012,0,21);